### ISSUE TITLE
No connection could be made

### ISSUE THREAD

**Issue by nbarkhina** [bmiller-net/Slingbox.Capture#2]
Hey there,

I'm trying to get the project running on my local network. I added the IP and password to my appsettings and then started debugging. However when it first goes to _slingboxService.Initialize() it's throwing an error "No connection could be made because the target machine actively refused it". Any ideas what else I could try?

![image](https://user-images.githubusercontent.com/10982154/99151333-66517200-2668-11eb-81ad-38f8945d4a86.png)

Thanks

**Comment by bmiller-net** [comment]
Which model Slingbox do you have? I have only tested this project on a Slingbox 500.

**Comment by bmiller-net** [comment]
Also, are you able to ping the Slingbox from your development machine? Mine does respond to ping requests.

**Comment by nbarkhina** [comment]
Yes it's a Slingbox 500 as well. Ping returns successfully 

![image](https://user-images.githubusercontent.com/10982154/99153645-b126b600-2677-11eb-90b8-3afd7ff98da5.png)

**Comment by bmiller-net** [comment]
I suppose it's possible not every device uses the same port, though I'm not sure exactly how I would determine an alternate. When I run nmap against mine, 5207 is not shown as an open port.

**Comment by bmiller-net** [comment]
Ok try this. Open a new tab in Chrome or Firefox, and open dev tools. Open the network tab. Navigate to newwatch.slingbox.com, log in if you have to.

One of the requests in the network window should be to the following URL: http://newwatch.slingbox.com/watch/slingAccounts/get_slingbox_sparcs_info/?finderId=your-finder-id&_=1605380817768

In the JSON response object, one of the fields is devicePort. If that is different that 5207, sub that in to the appsettings.json file.

**Comment by nbarkhina** [comment]
Yep mine was running on 5201. Now it works thanks!

![image](https://user-images.githubusercontent.com/10982154/99157693-50a87080-2699-11eb-88c8-75e4ed4d048f.png)

**Comment by bmiller-net** [comment]
Excellent. I wonder how the port number is determined. Something to look into... glad it's working!
